#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    liftAngleRight, sensorPotentiometer)
#pragma config(Sensor, in2,    liftAngleLeft,  sensorPotentiometer)
#pragma config(Sensor, in3,    coneAngleRight, sensorPotentiometer)
#pragma config(Sensor, in4,    coneAngleLeft,  sensorPotentiometer)
#pragma config(Sensor, in5,    lineLeft,       sensorNone)
#pragma config(Sensor, in6,    lineRight,      sensorNone)
#pragma config(Sensor, in7,    lineBack,       sensorNone)
#pragma config(Sensor, dgtl1,  extendLeft,     sensorDigitalOut)
#pragma config(Sensor, dgtl2,  extendRight,    sensorDigitalOut)
#pragma config(Sensor, dgtl3,  coneLock,       sensorDigitalOut)
#pragma config(Sensor, dgtl4,  mobleGoalLower, sensorTouch)
#pragma config(Sensor, dgtl5,  mobleGoalHigher, sensorTouch)
#pragma config(Sensor, I2C_1,  liftLowerRight, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  liftLowerLeft,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  leftDrive,      sensorNone)
#pragma config(Sensor, I2C_4,  rightDrive,     sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,            ,             tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           driveTrainRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           liftMobileLowerRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_4)
#pragma config(Motor,  port4,           liftMobileHigherRight, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           liftConeRight, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           liftConeLeft,  tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           liftMobileHigherLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveTrainLeft, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftMobileLowerLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port10,          coneIntake,    tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Sensors")
#pragma DebuggerWindows("Motors")
#pragma DebuggerWindows("Locals")
#pragma DebuggerWindows("Globals")

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


//bool mobileLowerIfTrue = true;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...






}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

bLCDBacklight = true;                                    // Turn on LCD Backlight
string mainBattery, backupBattery;
	// User control code here, inside the loop
	bool mobileForward = true;

	while (true)
	{

	clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
	clearLCDLine(1);                                            // Clear line 2 (1) of the LCD

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Backup battery voltage
	displayLCDString(1, 0, "Backup: ");
	sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');    //Build the value to be displayed
	displayNextLCDString(backupBattery);

	//Short delay for the LCD refresh rate
	wait1Msec(100);

		/*
		Drive
		Calls driveFunctions program to change motor speeds
		*/
		if(mobileForward){
				motor[port8] = vexRT[Ch3];
				motor[port2] = vexRT[Ch2];
		}
		else{

				motor[port8] = -(vexRT[Ch2]);
				motor[port2] = -(vexRT[Ch3]);

		}




		if(vexRT[Btn8U] == 1){
			mobileForward = false;
		}
		else if(vexRT[Btn8D] == 1){
			mobileForward = true;
		}



		//low lift
		if(vexRT[Btn5U] && mobileForward == true){
				//goes up

			motor[liftMobileLowerLeft] = 127;
			motor[liftMobileLowerRight] = 127;

			/* potential code for moving lower moble goal up (NEEDS TARGET)
			setMotorTarget(liftMobileLowerLeft, nEncoderCountTarget, 127, true);
    	setMotorTarget(liftMobileLowerRight, nEncoderCountTarget, 127, true);
			moveMotorTarget(liftMobileLowerLeft, nEncoderCountTarget, 127, true);
    	moveMotorTarget(liftMobileLowerRight, nEncoderCountTarget, 127, true);
    	*/

			}else if(vexRT[Btn5D] && mobileForward == true){
				//goes down

				motor[liftMobileLowerLeft] = -127;
				motor[liftMobileLowerRight] = -127;


			/* potential code for moving lower moble goal down (NEEDS TARGET)
			setMotorTarget(liftMobileLowerLeft, nEncoderCountTarget, -127, true);
    	setMotorTarget(liftMobileLowerRight, nEncoderCountTarget, -127, true);
			moveMotorTarget(liftMobileLowerLeft, nEncoderCountTarget, -127, true);
    	moveMotorTarget(liftMobileLowerRight, nEncoderCountTarget, -127, true);
    	*/


			}else{
			motor[liftMobileLowerLeft] = 0;
			motor[liftMobileLowerRight] = 0;
		}



		//High lift  (NEEDS SENSOR VALUES)
		if(vexRT[Btn6U] && mobileForward == true){
			//goes up
			motor[liftMobileHigherLeft] = 127;
			motor[liftMobileHigherRight] = 127;
			}else if(vexRT[Btn6D] && mobileForward == true){
			//goes down
			motor[liftMobileHigherLeft] = -127;
			motor[liftMobileHigherRight] = -127;
			}else if (mobileForward == true){
			motor[liftMobileHigherLeft] = 0;
			motor[liftMobileHigherRight] = 0;
		}






		//Pneumatic Lift Systems
		if(vexRT[Btn7U] == 1){
			//Activates Mobile Lift Pneumatics
			SensorValue[extendLeft] = 1;
			SensorValue[extendRight] = 1;
		}
		else if(vexRT[Btn7D] == 1){
			//Deactivates Mobile Lift Pneumatics
				SensorValue[extendLeft] = 0;
			SensorValue[extendRight] = 0;
		}

		if(vexRT[Btn7L] == 1){
			//Activates Cone Lift Pneumatics
			SensorValue[coneLock] = 0;
		}
		else if(vexRT[Btn7R] == 1){
			//Deactivates Cone Lift Pneumatics
			SensorValue[coneLock] = 1;
		}

		//Cone lift

		if(vexRT[Btn5D] && mobileForward == false){
			motor[liftConeLeft] = 127;
			motor[liftConeRight] = 127;

		}else if(vexRT[Btn5U] && mobileForward == false){
			motor[liftConeLeft]  = -127;
			motor[liftConeRight] = -127;
		}else{
			motor[liftConeLeft]  = 0;
			motor[liftConeRight] = 0;
		}

		//cone intake

		if(vexRT[Btn6U] && mobileForward == false){
			motor[coneIntake] = 127;

		}else if(vexRT[Btn6D] && mobileForward == false){
			motor[coneIntake]  = -127;
		}else if(mobileForward == false){
			motor[coneIntake]  = 0;
		}
	}
}
